//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaStack.Bus {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BusMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BusMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FaStack.Bus.BusMessages", typeof(BusMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initiating the mediator call.
        /// </summary>
        public static string CallingMediator {
            get {
                return ResourceManager.GetString("CallingMediator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an exception in the mediator call.
        /// </summary>
        public static string MediatorCallError {
            get {
                return ResourceManager.GetString("MediatorCallError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mediator successfully called.
        /// </summary>
        public static string MediatorSuccess {
            get {
                return ResourceManager.GetString("MediatorSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding notification to notification store.
        /// </summary>
        public static string Notifying {
            get {
                return ResourceManager.GetString("Notifying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were no message validation failures.
        /// </summary>
        public static string NoValidationFailures {
            get {
                return ResourceManager.GetString("NoValidationFailures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing event publishing.
        /// </summary>
        public static string Publishing {
            get {
                return ResourceManager.GetString("Publishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending event publishing.
        /// </summary>
        public static string PublishingEnd {
            get {
                return ResourceManager.GetString("PublishingEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing querying.
        /// </summary>
        public static string Querying {
            get {
                return ResourceManager.GetString("Querying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending querying.
        /// </summary>
        public static string QueryingEnd {
            get {
                return ResourceManager.GetString("QueryingEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing command sending.
        /// </summary>
        public static string Sending {
            get {
                return ResourceManager.GetString("Sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending command sending.
        /// </summary>
        public static string SendingEnd {
            get {
                return ResourceManager.GetString("SendingEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing message validating.
        /// </summary>
        public static string Validating {
            get {
                return ResourceManager.GetString("Validating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some flaws were found in the validation.
        /// </summary>
        public static string ValidationFailluresFound {
            get {
                return ResourceManager.GetString("ValidationFailluresFound", resourceCulture);
            }
        }
    }
}
